Category.create(topic:"Hospitality and Travel")
Category.create(topic:"Science and Pharmaceutical Research")
Category.create(topic:"Health and Medical")
Category.create(topic:"Retail")
Category.create(topic:"Arts, Media and Publishing")
Category.create(topic:"Legal")
Category.create(topic:"Automotive")
Category.create(topic:"Software Engineeing")
Category.create(topic:"Marketing")
Category.create(topic:"IT")

